import React from 'react';
import { useForm } from '@inertiajs/react';
import Button from '@/Components/Button';

export default function AddMedicineModal({ isOpen, onClose }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        generic_name: '',
        brand_name: '',
        category: '',
        dosage: '',
        reorder_point: 10,
        price_per_unit: '',
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('inventory.store'), {
            onSuccess: () => {
                reset();
                onClose();
            },
        });
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-fade-in">
            <div className="bg-white rounded-lg shadow-2xl w-full max-w-2xl overflow-hidden transform transition-all">
                
                {/* Header */}
                <div className="bg-[#2E4696] px-6 py-4 flex justify-between items-center border-b border-[#1e3a8a]">
                    <div>
                        <h2 className="text-white font-bold text-lg tracking-wide">ADD NEW MEDICINE</h2>
                        <p className="text-blue-200 text-xs mt-0.5">SKU will be auto-generated by the system</p>
                    </div>
                    <button onClick={onClose} className="text-white/70 hover:text-white text-2xl font-bold leading-none">&times;</button>
                </div>

                {/* Form */}
                <form onSubmit={handleSubmit} className="p-8">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        
                        <div className="md:col-span-2 flex gap-4">
                            <div className="flex-1">
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Generic Name <span className="text-red-500">*</span></label>
                                <input 
                                    type="text" 
                                    value={data.generic_name}
                                    onChange={e => setData('generic_name', e.target.value)}
                                    className="w-full border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5"
                                    placeholder="e.g. Paracetamol"
                                />
                                {errors.generic_name && <div className="text-red-500 text-xs mt-1 font-medium">{errors.generic_name}</div>}
                            </div>
                            
                            <div className="flex-1">
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Brand Name (Optional)</label>
                                <input 
                                    type="text" 
                                    value={data.brand_name}
                                    onChange={e => setData('brand_name', e.target.value)}
                                    className="w-full border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5"
                                    placeholder="e.g. Biogesic"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Category <span className="text-red-500">*</span></label>
                            <select 
                                value={data.category} 
                                onChange={e => setData('category', e.target.value)}
                                className="w-full border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5 bg-white"
                            >
                                <option value="">Select Category...</option>
                                <option value="Antibiotic">Antibiotic</option>
                                <option value="Analgesic">Analgesic (Painkiller)</option>
                                <option value="Vitamin">Vitamin</option>
                                <option value="Antihistamine">Antihistamine</option>
                                <option value="Anti-Inflammatory">Anti-Inflammatory</option>
                                <option value="Other">Other</option>
                            </select>
                            {errors.category && <div className="text-red-500 text-xs mt-1 font-medium">{errors.category}</div>}
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Dosage / Form <span className="text-red-500">*</span></label>
                            <input 
                                type="text" 
                                value={data.dosage}
                                onChange={e => setData('dosage', e.target.value)}
                                className="w-full border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5"
                                placeholder="e.g. 500mg Tablet"
                            />
                            {errors.dosage && <div className="text-red-500 text-xs mt-1 font-medium">{errors.dosage}</div>}
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Price Per Unit (₱) <span className="text-red-500">*</span></label>
                            <div className="relative">
                                <span className="absolute left-3 top-2.5 text-slate-400">₱</span>
                                <input 
                                    type="number" 
                                    step="0.01"
                                    value={data.price_per_unit}
                                    onChange={e => setData('price_per_unit', e.target.value)}
                                    className="w-full pl-7 border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5"
                                    placeholder="0.00"
                                />
                            </div>
                            {errors.price_per_unit && <div className="text-red-500 text-xs mt-1 font-medium">{errors.price_per_unit}</div>}
                        </div>

                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Low Stock Alert Level</label>
                            <input 
                                type="number" 
                                value={data.reorder_point}
                                onChange={e => setData('reorder_point', e.target.value)}
                                className="w-full border-slate-300 rounded-md shadow-sm focus:ring-[#2E4696] focus:border-[#2E4696] text-sm py-2.5"
                            />
                        </div>
                    </div>

                    <div className="mt-8 flex justify-end gap-3 border-t pt-6">
                        {/* Gray Cancel Button */}
                        <Button 
                            variant="gray" 
                            onClick={onClose}
                        >
                            CANCEL
                        </Button>
                        
                        <Button 
                            type="submit" 
                            variant="success"
                            disabled={processing}
                            className="flex items-center gap-2 px-6"
                        >
                            {processing && (
                                <svg className="animate-spin h-3 w-3 text-white" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                            )}
                            {processing ? 'CREATING...' : 'CREATE MEDICINE'}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    );
}